//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insonnia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insonnia.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏳ Rimanenti: {0}.
        /// </summary>
        internal static string Balloon_75Text {
            get {
                return ResourceManager.GetString("Balloon_75Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancora un po&apos;.
        /// </summary>
        internal static string Balloon_75Title {
            get {
                return ResourceManager.GetString("Balloon_75Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Meno di {0} rimasti.
        /// </summary>
        internal static string Balloon_90Text {
            get {
                return ResourceManager.GetString("Balloon_90Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In avvicinamento.
        /// </summary>
        internal static string Balloon_90Title {
            get {
                return ResourceManager.GetString("Balloon_90Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔 Scadenza tra {0}.
        /// </summary>
        internal static string Balloon_95Text {
            get {
                return ResourceManager.GetString("Balloon_95Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quasi scaduto.
        /// </summary>
        internal static string Balloon_95Title {
            get {
                return ResourceManager.GetString("Balloon_95Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏰ Tempo scaduto — buona notte!.
        /// </summary>
        internal static string Balloon_Expired {
            get {
                return ResourceManager.GetString("Balloon_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insonnia attivo {0}.
        /// </summary>
        internal static string Balloon_StartedText {
            get {
                return ResourceManager.GetString("Balloon_StartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviato.
        /// </summary>
        internal static string Balloon_StartedTitle {
            get {
                return ResourceManager.GetString("Balloon_StartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per {0}.
        /// </summary>
        internal static string Balloon_StartFor {
            get {
                return ResourceManager.GetString("Balloon_StartFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a tempo indeterminato.
        /// </summary>
        internal static string Balloon_StartIndefinite {
            get {
                return ResourceManager.GetString("Balloon_StartIndefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insonnia disattivato.
        /// </summary>
        internal static string Balloon_StoppedText {
            get {
                return ResourceManager.GetString("Balloon_StoppedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermato.
        /// </summary>
        internal static string Balloon_StoppedTitle {
            get {
                return ResourceManager.GetString("Balloon_StoppedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏰ Insonnia si ferma tra {0} secondi.
        /// </summary>
        internal static string Balloon_UrgentText {
            get {
                return ResourceManager.GetString("Balloon_UrgentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scadenza imminente!.
        /// </summary>
        internal static string Balloon_UrgentTitle {
            get {
                return ResourceManager.GetString("Balloon_UrgentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 ora.
        /// </summary>
        internal static string Duration_1h {
            get {
                return ResourceManager.GetString("Duration_1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 ore.
        /// </summary>
        internal static string Duration_2h {
            get {
                return ResourceManager.GetString("Duration_2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minuti.
        /// </summary>
        internal static string Duration_30min {
            get {
                return ResourceManager.GetString("Duration_30min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 ore.
        /// </summary>
        internal static string Duration_4h {
            get {
                return ResourceManager.GetString("Duration_4h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizzato....
        /// </summary>
        internal static string Duration_Custom {
            get {
                return ResourceManager.GetString("Duration_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∞  Sempre attivo.
        /// </summary>
        internal static string Duration_Infinite {
            get {
                return ResourceManager.GetString("Duration_Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfinito.
        /// </summary>
        internal static string Level_Exhausted {
            get {
                return ResourceManager.GetString("Level_Exhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attivo.
        /// </summary>
        internal static string Level_Happy {
            get {
                return ResourceManager.GetString("Level_Happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inattivo.
        /// </summary>
        internal static string Level_Off {
            get {
                return ResourceManager.GetString("Level_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sveglio.
        /// </summary>
        internal static string Level_Quiet {
            get {
                return ResourceManager.GetString("Level_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanco.
        /// </summary>
        internal static string Level_Weary {
            get {
                return ResourceManager.GetString("Level_Weary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizzato: {0} min.
        /// </summary>
        internal static string Menu_CustomMinutes {
            get {
                return ResourceManager.GetString("Menu_CustomMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata.
        /// </summary>
        internal static string Menu_Duration {
            get {
                return ResourceManager.GetString("Menu_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esci.
        /// </summary>
        internal static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra....
        /// </summary>
        internal static string Menu_Show {
            get {
                return ResourceManager.GetString("Menu_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶  Avvia.
        /// </summary>
        internal static string Menu_Start {
            get {
                return ResourceManager.GetString("Menu_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia con Windows.
        /// </summary>
        internal static string Menu_StartWithWindows {
            get {
                return ResourceManager.GetString("Menu_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■  Pausa.
        /// </summary>
        internal static string Menu_Stop {
            get {
                return ResourceManager.GetString("Menu_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insonnia è già in esecuzione..
        /// </summary>
        internal static string Msg_AlreadyRunning {
            get {
                return ResourceManager.GetString("Msg_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insonnia — Attivo da: {0}.
        /// </summary>
        internal static string Tray_ActiveElapsed {
            get {
                return ResourceManager.GetString("Tray_ActiveElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insonnia — Rimane: {0}.
        /// </summary>
        internal static string Tray_ActiveRemaining {
            get {
                return ResourceManager.GetString("Tray_ActiveRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insonnia - In pausa.
        /// </summary>
        internal static string Tray_Paused {
            get {
                return ResourceManager.GetString("Tray_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶  Avvia.
        /// </summary>
        internal static string UI_BtnStart {
            get {
                return ResourceManager.GetString("UI_BtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■  Stop.
        /// </summary>
        internal static string UI_BtnStop {
            get {
                return ResourceManager.GetString("UI_BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata:.
        /// </summary>
        internal static string UI_LabelDuration {
            get {
                return ResourceManager.GetString("UI_LabelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string UI_LabelMinutes {
            get {
                return ResourceManager.GetString("UI_LabelMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☕ {0}  —  Attivo da: {1}.
        /// </summary>
        internal static string UI_StatusActive {
            get {
                return ResourceManager.GetString("UI_StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In pausa.
        /// </summary>
        internal static string UI_StatusPaused {
            get {
                return ResourceManager.GetString("UI_StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱ {0}  —  Rimanente: {1}.
        /// </summary>
        internal static string UI_StatusTimer {
            get {
                return ResourceManager.GetString("UI_StatusTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☕ Insonnia.
        /// </summary>
        internal static string UI_Title {
            get {
                return ResourceManager.GetString("UI_Title", resourceCulture);
            }
        }
    }
}
